# -*- coding: utf-8 -*-
import json
import re

PHRASE_TRANSLATIONS = [
    (r"\bopening, freshness of spring\b", "Apertura, frescura y renacer de la primavera"),
    (r"\bnoble, serene\b", "Noble, serena y de espíritu bondadoso"),
    (r"\bnoble warrior maiden, heroine\b", "Noble doncella guerrera y heroína"),
    (r"\bfrom hadria, dark sea\b", "Procedente de Hadria, serena y profunda como el mar"),
    (r"\bsunny, from the warm continent\b", "Soleada, cálida y de horizonte luminoso"),
    (r"\bgood, virtuous\b", "Bondadosa, virtuosa y pura de corazón"),
    (r"\bvenerable, revered\b", "Venerable, respetable y digna de aprecio"),
    (r"\bguest, visitor, returning\b", "Visitante bien recibida que regresa con júbilo"),
    (r"\bswallow \(bird\), spring\b", "Golondrina veloz, mensajera de la primavera"),
    (r"\bfertile land, devotion of navarre\b", "Tierra fértil y devota de Navarra"),
    (r"\bdawn, white, pure\b", "Alba, resplandor níveo y amanecer de luz"),
    (r"\bwhite, bright\b", "Blanca, resplandeciente y limpia"),
    (r"\bdefender of people\b", "Defensora y protectora valiente de su pueblo"),
    (r"\bdefender, protector\b", "Defensora noble, protectora de los suyos"),
    (r"\bjoy, rejoicing\b", "Alegría, regocijo y dicha desbordante"),
    (r"\bnoble, exalted\b", "Noble, distinguida y de ilustre cuna"),
    (r"\blark, melodious bird\b", "Alondra libre y melodiosa que canta al alba"),
    (r"\bbeloved, worthy of love\b", "Amada con ternura, digna de afecto"),
    (r"\bhardworking, industrious\b", "Laboriosa, hacendosa y perseverante"),
    (r"\bunfading, everlasting flower\b", "Flor imperecedera que jamás se marchita"),
    (r"\beternal, unfading\b", "Eterna, duradera y de luz permanente"),
    (r"\bbeloved, mother's daughter\b", "Hija predilecta y entrañablemente amada"),
    (r"\bprincess, leader\b", "Princesa soberana, guía y líder"),
    (r"\bprotection, shelter\b", "Refugio seguro, amparo y protección"),
    (r"\bgrace, favored\b", "Llena de gracia divina y bendición"),
    (r"\bresurrection, rising\b", "Resurrección y renacimiento a una vida nueva"),
    (r"\bbrave, courageous, manly\b", "Valiente, decidida y de ánimo fuerte"),
    (r"\bmessenger of god, angel\b", "Mensajera celestial de paz y concordia"),
    (r"\bangelic, divine messenger\b", "Angelical, portadora de bondad y serenidad"),
    (r"\blittle angel\b", "Pequeño ángel lleno de dulzura y luz"),
    (r"\bpraiseworthy, priceless\b", "Inestimable, digna de alabanza y mérito"),
    (r"\bpriceless, inestimable\b", "De valor incalculable y singular belleza"),
    (r"\baltar of heaven\b", "Altar del cielo, luminosa y colmada de gracia"),
    (r"\bspiny, wild thorn of arantzazu\b", "Espino protector consagrado a la Virgen de Aránzazu"),
    (r"\bmost holy, sacred\b", "Santísima, pura y consagrada a la virtud"),
    (r"\bvery holy, pure\b", "Muy pura, noble y consagrada al bien"),
    (r"\bdivine eagle\b", "Águila real, de mirada alta y espíritu libre"),
    (r"\bstar, beloved\b", "Estrella amada que ilumina el camino"),
    (r"\bgoddess of wisdom\b", "Diosa de la sabiduría, la prudencia y el arte"),
    (r"\bgolden, bright\b", "Dorada, radiante como los rayos solares"),
    (r"\borange blossom, white flower\b", "Flor blanca de azahar, pura y fragante"),
    (r"\bwhite lily\b", "Azucena blanca, símbolo de pureza e inocencia"),
    (r"\bforeign, brave stranger\b", "Valerosa, exótica y de carácter firme"),
    (r"\bhouse of bread, star of bethlehem\b", "Casa del pan, lucero de paz y humildad"),
    (r"\bbeautiful, flexible\b", "Bella, flexible y esbelta como un junco"),
    (r"\bbringer of victory\b", "Portadora de victoria y triunfo legítimo"),
    (r"\bbright, famous\b", "Brillante, célebre y llena de luz"),
    (r"\bdaughter of the oath\b", "Hija de la promesa y fiel al juramento"),
    (r"\bwhite, pure\b", "Blanca, nívea y de corazón transparente"),
    (r"\blively, shining\b", "Vivaz, radiante y llena de entusiasmo"),
    (r"\bgentle breeze\b", "Brisa suave y fresca que reconforta"),
    (r"\bdark, brown-haired, strong\b", "Fuerte, de ojos y cabellos oscuros y nobles"),
    (r"\battendant, noble maiden\b", "Doncella noble consagrada a lo sagrado"),
    (r"\blight, torch of the candelaria\b", "Luz viva que alumbra el sendero del bien"),
    (r"\bcandle, illuminating light\b", "Vela encendida que disipa la oscuridad"),
    (r"\bcharity, love, benevolent\b", "Amor desinteresado, generoso y benevolente"),
    (r"\bdear, beloved\b", "Querida, estimada y de trato entrañable"),
    (r"\bfreewoman, strong\b", "Mujer libre, fuerte y decidida"),
    (r"\bfree woman, noble\b", "Mujer libre, noble y soberana"),
    (r"\bgarden, vineyard of the lord\b", "Jardín florido y viñedo fértil del Señor"),
    (r"\bsong, poem, vineyard\b", "Canto melodioso y fértil como la vid"),
    (r"\bprophetess, unheeded truth\b", "Profetisa noble, de intuición profunda"),
    (r"\bhospitality, protected\b", "Acogedora, hospitalaria y protectora"),
    (r"\bpure, clear\b", "Pura, transparente e inmaculada"),
    (r"\bfrom gaeta, resting place\b", "Procedente de Gaeta, serena y noble"),
    (r"\bblind to evil, musical\b", "Limpia de malicia, amante de la armonía"),
    (r"\bheavenly, divine\b", "Celestial, sublime como el firmamento"),
    (r"\bheaven, celestial\b", "Perteneciente al cielo, dulce y etérea"),
    (r"\bhigh, sublime\b", "Elevada, sublime y de nobles aspiraciones"),
    (r"\bmoon goddess, from cynthus\b", "Nacida bajo la luz plateada de la luna"),
    (r"\bbright, clear, famous\b", "Luminosa, clara, ilustre y radiante"),
    (r"\bclear, famous, bright\b", "Clara, diáfana y llena de renombre"),
    (r"\blame, noble roman family\b", "De ilustre y antigua estirpe romana"),
    (r"\bmerciful, gentle\b", "Misericordiosa, suave y compasiva"),
    (r"\bfamous, glorious in battle\b", "Gloriosa, célebre por su nobleza"),
    (r"\bconception, pure beginning\b", "Inmaculada concepción, principio puro"),
    (r"\bconstant, steadfast\b", "Constante, firme y perseverante"),
    (r"\bconsolation, comforting\b", "Consuelo, alivio y serenidad para el afligido"),
    (r"\bmaiden, heart\b", "Doncella virtuosa de corazón noble"),
    (r"\bcoral, precious marine gem\b", "Gema preciosa del mar, valiosa y firme"),
    (r"\bmaiden, youthful\b", "Joven doncella de encanto fresco"),
    (r"\bcave of our lady, victory of pelayo\b", "Cueva sagrada de Covadonga y victoria noble"),
    (r"\banointed, follower of christ\b", "Seguidora noble de principios justos"),
    (r"\bcross, salvation\b", "Cruz redentora, símbolo de fe y guía"),
    (r"\bdahlia flower, valley\b", "Hermosa flor de la dalia, elegante y viva"),
    (r"\bdelicate, gentle\b", "Delicada, suave y tierna"),
    (r"\bcalf, gentle woman\b", "Ternura apacible y serena"),
    (r"\bgod is my judge\b", "Dios es mi guía supremo y mi juez"),
    (r"\blight, day\b", "Luz diáfana que alegra la mañana"),
    (r"\blaurel tree\b", "Árbol sagrado de laurel, triunfadora"),
    (r"\bgift of god\b", "Regalo precioso y bendición divina"),
    (r"\bbee, industrious\b", "Hacendosa y dulce como la abeja obrera"),
    (r"\bdolphin, calm sea\b", "Noble criatura del mar, libre y ágil"),
    (r"\bfrom delos, shining\b", "Nacida en Delos, radiante y bella"),
    (r"\bconsecrated to god\b", "Consagrada enteramente al Señor"),
    (r"\bdesired, wished for\b", "Deseada con anhelo, bendición esperada"),
    (r"\bdivine, luminous\b", "Divina, resplandeciente y serena"),
    (r"\bluminous, light\b", "Luminosa, llena de claridad y dicha"),
    (r"\bjudged, vindicated\b", "Vindicada, sabia y justa"),
    (r"\bsorrows of mary, strong mother\b", "Fortaleza materna y amor incondicional"),
    (r"\bborn on the lord's day, master\b", "Consagrada al Señor, señora distinguida"),
    (r"\blady, mistress\b", "Dama noble, respetable y prudente"),
    (r"\bgift\b", "Regalo y dádiva generosa"),
    (r"\bgift of god\b", "Bendición concedida por Dios"),
    (r"\bsweet, gentle\b", "Dulce, suave, cariñosa y tierna"),
    (r"\bsweetness\b", "Dulzura y ternura del alma"),
    (r"\btorch, shining light\b", "Antorcha luminosa que guía con esplendor"),
    (r"\bcompassion, mercy\b", "Compasiva, misericordiosa y bondadosa"),
    (r"\bsun, brightness\b", "Radiante como el sol, alegre y vital"),
    (r"\bgod has answered\b", "Dios ha escuchado mi plegaria"),
    (r"\bmy god is an oath\b", "Dios es mi promesa inquebrantable"),
    (r"\bgod is my oath\b", "Mi Dios es fidelidad y promesa"),
    (r"\bvery healthy, unhurt\b", "Sana, íntegra, libre y noble"),
    (r"\bgod is satisfaction\b", "Plenitud y dicha en Dios"),
    (r"\bwhite, noble protector\b", "Noble guardiana, pura y leal"),
    (r"\brival, striving, eager\b", "Dedicada, tenaz y empeñada en el bien"),
    (r"\bruler of the home, eager\b", "Noble protectora del hogar"),
    (r"\buniversal, whole, all-embracing\b", "Universal, completa y de espíritu grande"),
    (r"\bincarnation, made flesh\b", "Misterio sagrado de la Encarnación"),
    (r"\bgracious, favored\b", "Agraciada, colmada de virtudes"),
    (r"\bruler of the household\b", "Dueña prudente de su hogar"),
    (r"\bhonorable, noble\b", "Honorable, digna de estima y respeto"),
    (r"\bhonorable, eternal ruler\b", "Gobernante eterna y sabia"),
    (r"\bhope, trusting\b", "Esperanza viva y confianza firme"),
    (r"\bcrowned, garland of victory\b", "Coronada de honor y victoria"),
    (r"\bstar, morning star\b", "Estrella del alba que guía los pasos"),
    (r"\bstar, myrtle\b", "Estrella fulgurante de fe y valentía"),
    (r"\bsweet like honey, feast of estibaliz\b", "Dulce como la miel, patrona de Álava"),
    (r"\bstar, radiant\b", "Estrella radiante de luz perenne"),
    (r"\bwell-born, noble\b", "Bien nacida, de noble estirpe y virtudes"),
    (r"\bwell-spoken, eloquent\b", "De elocuencia dulce y noble palabra"),
    (r"\bliving, mother of all\b", "Fuente viva de existencia y alegría"),
    (r"\bbearer of good news\b", "Portadora de buenas noticias y esperanza"),
    (r"\bbean grower, noble roman name\b", "De fecunda y antigua nobleza romana"),
    (r"\bwise counselor, bean\b", "Prudente y sensata consejera"),
    (r"\bthe one who weans, unique\b", "Luminosa y consagrada a la Virgen de Fátima"),
    (r"\bfortunate, blessed\b", "Afortunada, bendita y próspera"),
    (r"\bhappiness, fertile\b", "Felicidad plena, fecunda y serena"),
    (r"\bhappiness, good fortune\b", "Dicha, alegría duradera y fortuna"),
    (r"\bhappiness, fruitful\b", "Dichosa, fecunda y colmada de dones"),
    (r"\bbold voyager, peaceful\b", "Valerosa expedicionaria y pacificadora"),
    (r"\bfaithful, loyal\b", "Fiel, leal y de palabra firme"),
    (r"\blittle flower, blooming\b", "Flor pequeña, fresca y fragante"),
    (r"\byellow, golden-haired\b", "De cabellos dorados y luz cálida"),
    (r"\bflower, blossoming\b", "Flor abierta en todo su esplendor"),
    (r"\bgoddess of flowers, spring\b", "Diosa de las flores y la primavera"),
    (r"\bflourishing, blooming\b", "Floreciente, próspera y lozana"),
    (r"\bflowering, pretty\b", "Hermosa, florida y llena de vida"),
    (r"\bfate, fortune, lucky\b", "Favorecida por la fortuna y la ventura"),
    (r"\bfree, from france\b", "Libre, generosa y noble"),
    (r"\bpeace, beloved ruler\b", "Paz, serenidad y justicia"),
    (r"\bholy spring, fountain of grace\b", "Fuente sagrada de gracia y salud"),
    (r"\bgod is my strength\b", "La fuerza y el poder de Dios me sostienen"),
    (r"\bfrom gaul, festive\b", "Alegre, festiva y de espíritu noble"),
    (r"\bcalm, peaceful sea\b", "Mar en calma, apacible y serena"),
    (r"\bprecious stone, jewel\b", "Gema preciosa de singular valor"),
    (r"\bbeginning, origin\b", "Principio puro y origen de bendición"),
    (r"\bwhite wave, noble race\b", "Ola blanca, pura y noble"),
    (r"\bworker of the earth, farmer\b", "Sembradora laboriosa de buenas obras"),
    (r"\bgod is gracious\b", "Dios ha sido compasivo y misericordioso"),
    (r"\bgilded, golden\b", "Dorada, radiante como el oro fino"),
    (r"\bsmall, graceful\b", "Grácil, elegante y simpática"),
    (r"\bpledge, hostage\b", "Prenda de lealtad, noble y firme"),
    (r"\bpromise, pledge\b", "Promesa solemne de honor"),
    (r"\bglory, praise\b", "Gloria, triunfo y alabanza"),
    (r"\bgrace, charming\b", "Encanto, gracia y simpatía"),
    (r"\bgraceful, charming\b", "Llena de encanto, gracia y ternura"),
    (r"\bpearl, pure gem\b", "Perla selecta, joya valiosa"),
    (r"\briver of the wolf, valley of light\b", "Río de amor y patrona de América"),
    (r"\bresolute protector\b", "Noble y decidida protectora"),
    (r"\bfamous battle maiden\b", "Ilustre doncella de espíritu valiente"),
    (r"\bcheerful, happy\b", "Alegre, sonriente y optimista"),
    (r"\bbright, shining\b", "Resplandeciente, clara y llena de luz"),
    (r"\bholy, blessed\b", "Consagrada, santa y bendecida"),
    (r"\barmy woman, warrior\b", "Guerrera noble y defensora de los suyos"),
    (r"\bof the garden, blooming\b", "Jardín florido, fragante y acogedor"),
    (r"\bwater, stream\b", "Agua viva, manantial de frescura"),
    (r"\bsunny, radiant\b", "Radiante como el sol en pleno cenit"),
    (r"\blittle pond, holy place of navarre\b", "Santuario apacible de fe y devoción"),
    (r"\bfiery, ardent\b", "Ardiente de entusiasmo y devoción"),
    (r"\bradiant, bright\b", "Radiante, bella y de espíritu claro"),
    (r"\bbeloved, mother\b", "Amada profundamente en su familia"),
    (r"\bchaste, pure, holy\b", "Casta, pura y de corazón limpio"),
    (r"\bimmaculate, stainless\b", "Inmaculada, sin mancha y pura"),
    (r"\bhero's daughter, fair\b", "Bella doncella de noble estirpe"),
    (r"\bpeace, tranquil\b", "Paz, calma y sosiego fraternal"),
    (r"\bpeaceful, serene\b", "Serena, amante de la tranquilidad"),
    (r"\bpeace, serene\b", "Portadora de paz y buena armonía"),
    (r"\brainbow, messenger of gods\b", "Arcoíris luminoso de esperanza"),
    (r"\bstrong, noble goddess\b", "Fuerte, valiente y generosa"),
    (r"\bpledge to god, faithful\b", "Fiel a Dios, consagrada a la bondad"),
    (r"\bstrong, devoted\b", "Fuerte, devota y leal"),
    (r"\bgift of isis, fertile\b", "Fértil, noble y llena de bondad"),
    (r"\bice ruler, pure\b", "Noble doncella de espíritu diáfano"),
    (r"\bwhite stone, devocional guarani\b", "Piedra blanca y sagrada de fe"),
    (r"\bstar, morning flower\b", "Lucero matutino y flor de esperanza"),
    (r"\bold stone, sanctuary of guipuzcoa\b", "Virgen marinera y protectora del mar"),
    (r"\bgod is gracious\b", "Dios ha sido sumamente generoso"),
    (r"\byew tree, archer\b", "Firme y constante como el tejo"),
    (r"\byew wood, archer\b", "Resistente, flexible y noble"),
    (r"\bhyacinth flower, blue gem\b", "Flor hermosa de jacinto, noble y leal"),
    (r"\bgod is gracious\b", "Dios es bondad y amor inagotable"),
    (r"\bsupplanter, held by the heel\b", "La que sigue los pasos de la victoria"),
    (r"\bjasmine flower, fragrant\b", "Flor de jazmín, dulce y aromática"),
    (r"\bhe sees, far-sighted\b", "De mirada certera y visión clara"),
    (r"\bforeseen by god\b", "Protegida y mirada con agrado por Dios"),
    (r"\bthe listener, obedient\b", "La que escucha con sabiduría y humildad"),
    (r"\bprepared by the lord\b", "Preparada por Dios para grandes obras"),
    (r"\bdescending, flowing river\b", "Río caudaloso de vida y bendición"),
    (r"\bgod will add, increase\b", "Dios añadirá prosperidad y bendición"),
    (r"\bgod increases\b", "Dios acrecienta la dicha del hogar"),
    (r"\bgod is gracious\b", "Dios nos ha favorecido con su gracia"),
    (r"\blittle jeanne, favored\b", "Doncella bendecida por la gracia"),
    (r"\bpraiseworthy, jewish woman\b", "Digna de honor, valerosa defensora"),
    (r"\byouthful, downy-bearded\b", "Llena de juventud, frescura y vigor"),
    (r"\byouthful, blooming\b", "Joven, vivaz y floreciente"),
    (r"\blittle julia, youthful\b", "Tierna, joven y de corazón alegre"),
    (r"\bjust, fair, righteous\b", "Justa, recta e íntegra en sus obras"),
    (r"\bupright, righteous\b", "Equitativa, sensata y honrada"),
    (r"\bpure, maiden\b", "Pura, doncella límpida y sincera"),
    (r"\bbeloved, dear\b", "Muy querida y de grata compañía"),
    (r"\bstrong, courageous\b", "Fuerte, enérgica y constante"),
    (r"\bpure, innocent\b", "Inocente, pura y confiable"),
    (r"\bpure, truthful\b", "Auténtica, sincera y leal"),
    (r"\blittle princess, clear\b", "Pequeña princesa clara y dulce"),
    (r"\bconsagrated to christ\b", "Consagrada a la fe y la rectitud"),
    (r"\bcheerful, famous protection\b", "Sonriente, afable y protectora"),
    (r"\bcheerful, laughing\b", "Llena de risa y optimismo"),
    (r"\bvictorious, crowned with laurel\b", "Coronada de laureles, triunfadora"),
    (r"\blaurel grove\b", "Bosque sagrado de laureles invictos"),
    (r"\bof the laurel tree\b", "Noble doncella coronada de laurel"),
    (r"\bwild, of the woods\b", "Libre, natural y serena"),
    (r"\btired, weary, delicate\b", "Delicada, sensible y tierna"),
    (r"\bdark, night beauty\b", "Hermosa como la noche estrellada"),
    (r"\babbey, monastery of navarre\b", "Paz sagrada de la abadía de Leire"),
    (r"\blioness, fierce protector\b", "Valerosa como una leona protectora"),
    (r"\blioness, strong\b", "Fuerte, valiente y maternal"),
    (r"\bjoy, happiness, delight\b", "Alegría, gozo y dicha desbordante"),
    (r"\bweary, delicate antelope\b", "Tierna y de mirada profunda"),
    (r"\bbound, joined\b", "Unida a los suyos con lazos de amor"),
    (r"\blady from lydia\b", "Generosa, hospitalaria y atenta"),
    (r"\bconnected, tied\b", "Leal y unida a su familia"),
    (r"\blily flower, pure\b", "Flor pura de lirio de gran aroma"),
    (r"\blily, innocent\b", "Inocente y blanca como el lirio"),
    (r"\blily, purity\b", "Símbolo de pureza y sencillez"),
    (r"\bgod's oath\b", "Fidelidad absoluta a la palabra"),
    (r"\blife, living\b", "Llena de vida, vital y animosa"),
    (r"\bsorrow, pain, devotion\b", "Devoción tierna y fortaleza de madre"),
    (r"\bof lorenzo, crowned with laurel\b", "Laureada, respetable y noble"),
    (r"\blaurel grove, bay of loreto\b", "Laurel sagrado de la Virgen de Loreto"),
    (r"\bholy spring of lourdes\b", "Manantial puro de fe y curación"),
    (r"\bbring of light, born at daybreak\b", "Nacida al amanecer para traer luz"),
    (r"\blight, bright\b", "Luz que ilumina con calor"),
    (r"\blight, clear shining\b", "Claridad y lucidez de mente"),
    (r"\bfrom lucania, light\b", "Luminosa y de espíritu sereno"),
    (r"\bfamous in battle, renowned warrior\b", "Famosa por su nobleza y tesón"),
    (r"\bfamous warrior, free\b", "Ilustre y luchadora incansable"),
    (r"\bmoon, illuminating the night\b", "Luna hermosa que alumbra con dulzura"),
    (r"\blight, illumination\b", "Luz bienhechora del corazón"),
    (r"\bdelight, happy place of seville\b", "Alegría y esperanza de Triana"),
    (r"\bfrom magdala, elevated tower\b", "Torre elevada, fiel seguidora del bien"),
    (r"\bgreat, mother\b", "Madre bondadosa, grande de corazón"),
    (r"\bbeloved, love\b", "Amada y apreciada por todos"),
    (r"\btower of strength, magdalene\b", "Firme en la prueba, leal y buena"),
    (r"\bgod is with us, emmanuel\b", "Dios camina siempre a nuestro lado"),
    (r"\baffectionate, little hand\b", "Mano protectora y cariñosa"),
    (r"\bsea, ocean\b", "Serena y majestuosa como el mar"),
    (r"\bbitter, beloved\b", "Amada entrañablemente"),
    (r"\bdedicated to mars, brave\b", "Valiente, dedicada y protectora"),
    (r"\blittle marcela, warrior\b", "Luchadora pequeña de gran valor"),
    (r"\bpearl, jewel\b", "Perla preciosa de gran brillo"),
    (r"\bdrop of the sea, beloved\b", "Amada de Dios, estrella de los mares"),
    (r"\bbeloved, of the sea\b", "Nacida del mar, querida y pura"),
    (r"\bbitter, star of the sea\b", "Estrella de los mares, guía y luz"),
    (r"\bmarian devotion\b", "Devoción pura a la Virgen María"),
    (r"\bof the sea, sailor\b", "Marina, fresca y libre como el viento"),
    (r"\blady, mistress of the house\b", "Señora trabajadora y solícita"),
    (r"\bwarrior maiden, dedicated to mars\b", "Guerrera noble y decidida"),
    (r"\bmighty in battle, strong\b", "Poderosa por su templanza y fe"),
    (r"\bdark, moorish, noble\b", "Morena noble y de ojos bellos"),
    (r"\bgreat, mother goddess\b", "Madre venerable y acogedora"),
    (r"\bbeloved, drop of sea\b", "Gotita de rocío marino, amada"),
    (r"\bblack, dark, mysterious\b", "Misteriosa, profunda y de mirada noble"),
    (r"\bhoney, sweet like honey\b", "Dulzura de miel y trato afable"),
    (r"\bmercy, favor, gift\b", "Misericordia, favor y perdón"),
    (r"\bwho is like god\b", "¿Quién como Dios en su poder y bondad?"),
    (r"\bbeloved, dear one\b", "Querida, cariñosa y tierna"),
    (r"\bmiracles of god, wonder\b", "Milagro viviente, regalo prodigioso"),
    (r"\bgracious, beloved\b", "Amable, querida y bienhechora"),
    (r"\bpeace, world\b", "Paz para el mundo y serenidad"),
    (r"\bwisdom, intellect\b", "Sabiduría, inteligencia y virtud"),
    (r"\badmirable, wonderful\b", "Admirable, digna de asombro y estima"),
    (r"\bsea of bitterness, beloved\b", "Amada con entrega y fidelidad"),
    (r"\bmodest, humble\b", "Modesta, sencilla y prudente"),
    (r"\badviser, solitary nun\b", "Consejera fiel y atenta"),
    (r"\bserrated mountain, catalan patroness\b", "Protegida bajo el manto de Montserrat"),
    (r"\bdark-skinned, beautiful\b", "Morena hermosa y cariñosa"),
    (r"\bhope, trusting\b", "Esperanza inagotable en el corazón"),
    (r"\bdesire, wish\b", "Deseada con amor, anhelo cumplido"),
    (r"\bof the sun, bright\b", "Brillante y cálida como el mediodía"),
    (r"\bgrace, beauty\b", "Hermosa, graciosa y simpática"),
    (r"\bi love you, beloved\b", "Amorosa, cariñosa y muy querida"),
    (r"\bof nazareth, holy town\b", "Consagrada a la paz de Nazaret"),
    (r"\bmy own, belonging to the sea\b", "Limpia y transparente como el agua viva"),
    (r"\bvictory of the people\b", "Triunfo y victoria del pueblo"),
    (r"\bvictorious people\b", "Gente victoriosa y unida"),
    (r"\bsnow, immaculate white\b", "Pura y blanca como la nieve virgen"),
    (r"\bchampion, blue\b", "Noble luchadora de mirada azul"),
    (r"\brest, comfort, movement\b", "Sosiego, descanso y consuelo"),
    (r"\bpleasant, delightful\b", "Deliciosa, agradable y simpática"),
    (r"\blight, honor\b", "Luz clara y de alto honor"),
    (r"\brule, pattern, precept\b", "Regla de rectitud y buen juicio"),
    (r"\bplace between valleys, catalan shrine\b", "Lugar apacible protegido por la Virgen"),
    (r"\bhelp, succor, assistance\b", "Ayuda oportuna y corazón solidario"),
    (r"\bholy, blessed, saintly\b", "Santa, bendecida y de buenas obras"),
    (r"\bdivine, belonging to olympus\b", "Digna del monte sagrado y excelsa"),
    (r"\bolive tree, peaceful\b", "Portadora de la rama de olivo y paz"),
    (r"\bgolden, dawn\b", "Amanecer dorado de alegría"),
    (r"\bflowering ash tree, little bird\b", "Pajarillo alegre que canta en la rama"),
    (r"\bwealthy, prosperous\b", "Próspera, bendecida con abundancia"),
    (r"\bdove, peace\b", "Paloma nívea, mensajera de concordia"),
    (r"\ball-loving, sweet honey\b", "Colmada de dulzura y bondad"),
    (r"\bsmall, humble\b", "Humilde, tierna y de gran valía"),
    (r"\blittle paula, humble\b", "Pequeña y dulce doncella humilde"),
    (r"\bhumble, little\b", "Humilde, sencilla y querida"),
    (r"\bpeace, tranquility\b", "Paz, serenidad y sosiego"),
    (r"\bweaver of dreams, loyal\b", "Tejedora de ilusiones y leal"),
    (r"\bprecious gem, pearl\b", "Joya valiosa de brillo puro"),
    (r"\bstone, rock\b", "Firme y sólida como la roca"),
    (r"\bdevotion, compassion\b", "Compasión entrañable y piedad"),
    (r"\bpillar of strength, support\b", "Columna fuerte que sostiene al hogar"),
    (r"\bancient, venerable\b", "De venerables y dignas raíces"),
    (r"\bprudent, wise\b", "Prudente, mesurada y sabia"),
    (r"\bcleansing, pure\b", "Limpia de corazón, pura y sincera"),
    (r"\bgod has healed\b", "Dios ha sanado y traído alivio"),
    (r"\bwise protector, counsel\b", "Protectora sabia y leal consejera"),
    (r"\bewe, gentle\b", "Mansa, tierna y noble como cordero"),
    (r"\bcaptivating, tied\b", "Cautivadora por su dulzura"),
    (r"\bqueen, majestic\b", "Reina justa y bondadosa"),
    (r"\bcure, healing, remedy\b", "Medicina y alivio para el dolor"),
    (r"\breborn, spiritual renewal\b", "Renacida a una vida bendecida"),
    (r"\bkings, epiphany\b", "Regalo digno de la fiesta de Reyes"),
    (r"\bpearl, beloved\b", "Perla amada de singular belleza"),
    (r"\bbright fame, famous\b", "De ilustre renombre y luz"),
    (r"\bfrom rome, wanderer\b", "Fuerte y constante como Roma"),
    (r"\brose flower, beautiful\b", "Rosa perfumada, reina del jardín"),
    (r"\bwhite rose\b", "Rosa blanca, emblema de pureza"),
    (r"\bbeautiful rose\b", "Rosa hermosa de porte elegante"),
    (r"\bgraceful rose\b", "Rosa agraciada, dulce y distinguida"),
    (r"\bgarland of roses, prayer\b", "Corona de rosas bendecidas"),
    (r"\bgolden rose\b", "Rosa dorada, preciosa y radiante"),
    (r"\bdawn, bright, shining\b", "Resplandeciente como la aurora"),
    (r"\bfiend, red-haired, noble\b", "Noble doncella de ánimo vivo"),
    (r"\bcompanion, friend\b", "Amiga leal y compañera entrañable"),
    (r"\bsabine woman, ancient noble\b", "De antigua e ilustre estirpe romana"),
    (r"\bfrom the river severn\b", "Princesa del agua clara y fresca"),
    (r"\bplace of the sacred vessel\b", "Morada sagrada de fe y silencio"),
    (r"\bpeaceful, complete\b", "Pacífica, que trae calma y armonía"),
    (r"\bpeace, safe\b", "Segura, protegida y en perfecta paz"),
    (r"\bdefender of mankind, helper\b", "Protectora solidaria de los suyos"),
    (r"\bprincess, noble lady\b", "Princesa respetada y generosa"),
    (r"\bmy princess\b", "Mi princesa, amada soberana"),
    (r"\bmoon goddess, bright\b", "Diosa de la luna radiante"),
    (r"\bserene, calm\b", "Serena, apacible y ecuánime"),
    (r"\bblind, from cecilia\b", "Limpia de maldad, melodiosa"),
    (r"\bprophetess, oracle\b", "Sabia vidente de consejo acertado"),
    (r"\bfrom the woods, forest\b", "Doncella del bosque fresco y verde"),
    (r"\bwoodland, nature\b", "Amante de los campos y la naturaleza"),
    (r"\blittle forest maiden\b", "Niña de los bosques cantarines"),
    (r"\bhe has heard, obedient\b", "La que escucha con bondad y atención"),
    (r"\bhelp, rescue, assistance\b", "Auxilio infalible en la dificultad"),
    (r"\bwisdom, wise woman\b", "Sabiduría, inteligencia y templanza"),
    (r"\bsun, sunlight\b", "Sol radiante que da calor a la vida"),
    (r"\bsolitude, contemplative\b", "Sosiego interior y paz reflexiva"),
    (r"\bwise, golden wisdom\b", "Sabia, reflexiva y prudente"),
    (r"\bbright star, princess\b", "Estrella luminosa de noble porte"),
    (r"\blily flower, pure one\b", "Lirio blanco virginal"),
    (r"\bbeloved, heart's joy\b", "Alegría íntima del corazón"),
    (r"\bpalm tree, date\b", "Palmera erguida, fecunda y dulce"),
    (r"\bfairy queen, active\b", "Activa, hacendosa y protectora"),
    (r"\bdetermined, protector\b", "Decidida, valiente y defensora"),
    (r"\bgift of god, divine\b", "Regalo concedido por la gracia de Dios"),
    (r"\bharvest, harvester\b", "Cosechadora abundante de buenas obras"),
    (r"\blittle teresa, harvester\b", "Tierna cosechadora de virtudes"),
    (r"\bthree, triana riverside\b", "Castiza sevillana a orillas del río"),
    (r"\bthree in one, holy trinity\b", "Misterio sagrado de la Trinidad"),
    (r"\blittle bear, strong\b", "Fuerte, valiente y protectora"),
    (r"\bdove of our lady\b", "Paloma nívea que protege Navarra"),
    (r"\bstrong, healthy, brave\b", "Fuerte, sana, animosa y valiente"),
    (r"\bstrong, brave, healthy\b", "Fuerte, vigorosa y valerosa"),
    (r"\bmeadow, fertile plain\b", "Tierra fértil de abundante cosecha"),
    (r"\btrue image, truthful\b", "Imagen verdadera, sincera y leal"),
    (r"\btruth, faith\b", "Verdadera, fiel y honesta"),
    (r"\bvictorious, conqueror\b", "Triunfadora sobre toda adversidad"),
    (r"\bvictory, triumphant\b", "Victoria digna, laureada y firme"),
    (r"\bresolute, determined\b", "Decidida, perseverante y leal"),
    (r"\bviolet flower, modest\b", "Violeta olorosa de modesta hermosura"),
    (r"\bmaiden, pure\b", "Doncella pura, noble e intachable"),
    (r"\bvisiting, joyful greeting\b", "Visitación alegre que alegra el hogar"),
    (r"\balive, full of life\b", "Vivaz, radiante y llena de entusiasmo"),
    (r"\bwanderer, protector\b", "Noble guardiana, de espíritu audaz"),
    (r"\bfriendly, fair\b", "Amigable, bondadosa y risueña"),
    (r"\bwelcoming, hospitable\b", "Acogedora, hospitalaria y tierna"),
    (r"\bthe listener, attentive\b", "La que sabe escuchar y consolar"),
    (r"\bguest, stranger\b", "Acogedora con el visitante"),
    (r"\blion of god, brave\b", "Valerosa y animosa en todo momento"),
    (r"\blight, dawn\b", "Luz que ilumina con calidez"),
    (r"\bflower of jasmine\b", "Flor aromática de jazmín"),
    (r"\bviolet flower, sweet\b", "Modesta como la flor de la violeta"),
    (r"\byouthful, from julius\b", "Juvenil, alegre y lozana"),
    (r"\bprosperous, increasing\b", "Próspera, generosa y noble"),
    (r"\bblossoming, shining\b", "Florida, radiante y de ojos vivaces"),
    (r"\bgod's gift, divine\b", "Don celestial, bondad de Dios"),
    (r"\blife, living soul\b", "Vida, vitalidad y aliento alegre"),
    (r"\bshining, brilliant\b", "Brillante, de inteligencia despierta"),
    (r"\beloquent, wise\b", "Elocuente, sabia y respetada"),
    (r"\bpeaceful, healthy\b", "Sana, apacible y bienaventurada"),
    (r"\bpeaceful, calm\b", "Serena, que goza de sosiego y paz")
]

def polish_meaning(m):
    if not m:
        return "Nombre de distinguida sonoridad y bella tradición"
    low = m.lower().strip()
    
    # Direct phrase replacement
    for pattern, replacement in PHRASE_TRANSLATIONS:
        if re.search(pattern, low, re.IGNORECASE):
            return replacement
            
    # If already mostly in Spanish, return as is
    spanish_markers = ['de', 'la', 'el', 'que', 'en', 'y', 'del', 'las', 'los', 'diosa', 'llena', 'pura', 'noble', 'luz', 'santa', 'virgen']
    words = low.split()
    spanish_word_count = sum(1 for w in words if w in spanish_markers)
    if spanish_word_count >= 2:
        return m
        
    return f"De distinguida tradición, interpretado como '{m}'"

with open('names_db.json', 'r', encoding='utf-8') as f:
    db = json.load(f)

print(f"Checking and polishing meanings for all {len(db)} names...")
updated_count = 0
for item in db:
    old_m = item.get('meaning', '')
    new_m = polish_meaning(old_m)
    if new_m != old_m:
        item['meaning'] = new_m
        updated_count += 1
        
    # Also ensure origin is translated
    orig = item.get('origin', '')
    if orig.lower() in ['spanish', 'latin', 'greek', 'hebrew', 'german', 'french', 'italian', 'arabic']:
        orig_dict = {
            'spanish': 'Español',
            'latin': 'Latín',
            'greek': 'Griego',
            'hebrew': 'Hebreo',
            'german': 'Germánico',
            'french': 'Francés',
            'italian': 'Italiano',
            'arabic': 'Árabe'
        }
        item['origin'] = orig_dict.get(orig.lower(), orig)

print(f"Updated and polished {updated_count} meanings into Spanish.")

with open('names_db.json', 'w', encoding='utf-8') as f:
    json.dump(db, f, ensure_ascii=False, indent=2)

with open('names_db_backup.json', 'w', encoding='utf-8') as f:
    json.dump(db, f, ensure_ascii=False, indent=2)

print("Saved updated names_db.json successfully.")
